[package]
name = "rustlearning"
version = "0.1.0"
authors = ["CAFEBABE <neuropathycc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = {version = "0.7.6", features=["tcp", "os-poll"]}
rand = "0.7"
[profile.release]
panic = 'abort'